services:
  chain-node:
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 8G

  api:
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 2G
